apiVersion: v1
kind: Namespace
metadata:
  name: fdo-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: fdo-operator
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: fdo-operator
  source: fdo-operators
  sourceNamespace: openshift-marketplace
