apiVersion: v1
kind: Namespace
metadata:
  name: fdo-operator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fdo-manufacturing-config
  namespace: fdo-operator
data:
  manufacturing-server.yml: |
    session_store_driver:
      Directory:
        path: /etc/fdo/sessions/
    ownership_voucher_store_driver:
      Directory:
        path: /etc/fdo/ownership_vouchers/
    public_key_store_driver:
      Directory:
        path: /etc/fdo/keys/
    bind: 0.0.0.0:8080
    rendezvous_info:
    - ip: fdo-rendezvous.apps-crc.testing
      device_port: 8082
      owner_port: 8082
      protocol: http
    protocols:
      plain_di: false
      diun:
        key_path: /etc/fdo/keys/diun_key.der
        cert_path: /etc/fdo/keys/diun_cert.pem
        key_type: SECP256R1
        mfg_string_type: SerialNumber
        allowed_key_storage_types:
        - FileSystem
        - Tpm
    manufacturing:
      manufacturer_cert_path: /etc/fdo/keys/manufacturer_cert.pem
      manufacturer_private_key: /etc/fdo/keys/manufacturer_key.der
      owner_cert_path: /etc/fdo/keys/owner_cert.pem
      device_cert_ca_private_key: /etc/fdo/keys/device_ca_key.der
      device_cert_ca_chain: /etc/fdo/keys/device_ca_cert.pem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdo-manufacturing-deployment
  namespace: fdo-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdo-manufacturing
  template:
    metadata:
      labels:
        app: fdo-manufacturing
    spec:
      containers:
      - name: fdo-manufacturing-server
        image: 192.168.130.1:5000/fdo-manufacturing-server:latest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        ports:
          - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/fdo/manufacturing-server.conf.d
        - name: ownership-vouchers
          mountPath: /etc/fdo/ownership_vouchers
        - name: diun-key
          mountPath: /etc/fdo/keys/diun_key.der
          readOnly: true
        - name: diun-cert
          mountPath: /etc/fdo/keys/diun_cert.pem
          readOnly: true
        - name: manufacturer-cert
          mountPath: /etc/fdo/keys/manufacturer_cert.pem
          readOnly: true
        - name: manufacturer-key
          mountPath: /etc/fdo/keys/manufacturer_key.der
          readOnly: true
        - name: owner-cert
          mountPath: /etc/fdo/keys/owner_cert.pem
          readOnly: true
        - name: device-ca-key
          mountPath: /etc/fdo/keys/device_ca_key.der
          readOnly: true
        - name: device-ca-chain
          mountPath: /etc/fdo/keys/device_ca_cert.pem
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: fdo-manufacturing-config
      - name: diun-key
        secret:
          secretName: fdo-diun-key
          items:
            - key: diun_key.der
              path: diun_key.der
          optional: false
      - name: diun-cert
        secret:
          secretName: fdo-diun-cert
          items:
          - key: diun_cert.pem
            path: diun_cert.pem
          optional: false
      - name: manufacturer-cert
        secret:
          secretName: fdo-manufacturer-cert
          items:
          - key: manufacturer_cert.pem
            path: manufacturer_cert.pem
          optional: false
      - name: manufacturer-key
        secret:
          secretName: fdo-manufacturer-key
          items:
          - key: manufacturer_key.der
            path: manufacturer_key.der
          optional: false
      - name: owner-cert
        secret:
          secretName: fdo-owner-cert
          items:
          - key: owner_cert.pem
            path: owner_cert.pem
          optional: false
      - name: device-ca-key
        secret:
          secretName: fdo-device-ca-key
          items:
          - key: device_ca_key.der
            path: device_ca_key.der
          optional: false
      - name: device-ca-chain
        secret:
          secretName: fdo-device-ca-cert
          items:
          - key: device_ca_cert.pem
            path: device_ca_cert.pem
          optional: false
      - name: ownership-vouchers
        persistentVolumeClaim:
          claimName: ownership-vouchers-pvc
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ownership-vouchers-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ownership-vouchers-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/fdo"