apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "fdo.redhat.com/v1alpha1",
          "kind": "FDOManufacturingServer",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "fdo-operator",
              "app.kubernetes.io/instance": "fdomanufacturingserver-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "fdomanufacturingserver",
              "app.kubernetes.io/part-of": "fdo-operator"
            },
            "name": "fdomanufacturingserver-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "fdo.redhat.com/v1alpha1",
          "kind": "FDOOnboardingServer",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "fdo-operator",
              "app.kubernetes.io/instance": "fdoonboardingserver-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "fdoonboardingserver",
              "app.kubernetes.io/part-of": "fdo-operator"
            },
            "name": "fdoonboardingserver-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "fdo.redhat.com/v1alpha1",
          "kind": "FDORendezvousServer",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "fdo-operator",
              "app.kubernetes.io/instance": "fdorendezvousserver-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "fdorendezvousserver",
              "app.kubernetes.io/part-of": "fdo-operator"
            },
            "name": "fdorendezvousserver-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.25.0-ocp
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: fdo-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: FDOManufacturingServer is the Schema for the fdomanufacturingservers
        API
      displayName: FDOManufacturing Server
      kind: FDOManufacturingServer
      name: fdomanufacturingservers.fdo.redhat.com
      version: v1alpha1
    - description: FDOOnboardingServer is the Schema for the fdoonboardingservers
        API
      displayName: FDOOnboarding Server
      kind: FDOOnboardingServer
      name: fdoonboardingservers.fdo.redhat.com
      version: v1alpha1
    - description: FDORendezvousServer is the Schema for the fdorendezvousservers
        API
      displayName: FDORendezvous Server
      kind: FDORendezvousServer
      name: fdorendezvousservers.fdo.redhat.com
      version: v1alpha1
  description: The FDO Operator allows deploying one or more FIDO Device Onboard (FDO)
    servers - manufacturing, rendezvous, owner onboarding and service info API - based
    on the Fedora IoT implementation of FDO.
  displayName: FIDO Device Onboard (FDO) Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - fdo.redhat.com
          resources:
          - fdomanufacturingservers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - fdo.redhat.com
          resources:
          - fdomanufacturingservers/finalizers
          verbs:
          - update
        - apiGroups:
          - fdo.redhat.com
          resources:
          - fdomanufacturingservers/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - fdo.redhat.com
          resources:
          - fdoonboardingservers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - fdo.redhat.com
          resources:
          - fdoonboardingservers/finalizers
          verbs:
          - update
        - apiGroups:
          - fdo.redhat.com
          resources:
          - fdoonboardingservers/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - fdo.redhat.com
          resources:
          - fdorendezvousservers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - fdo.redhat.com
          resources:
          - fdorendezvousservers/finalizers
          verbs:
          - update
        - apiGroups:
          - fdo.redhat.com
          resources:
          - fdorendezvousservers/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: fdo-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: fdo-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: fdo-operator
          control-plane: controller-manager
        name: fdo-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.12
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: quay.io/vemporop/fdo-operator:1alpha1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: fdo-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: fdo-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - fdo
  - edge
  links:
  - name: Fdo Operator
    url: https://fdo-operator.domain
  maintainers:
  - email: vemporop@redhat.com
    name: Vitaliy Emporopulo
  maturity: alpha
  provider:
    name: Red Hat
    url: https://github.com/empovit/fdo-operator
  version: 0.0.1
