---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - fdo.example.com
  resources:
  - fdomanufacturingservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fdo.example.com
  resources:
  - fdomanufacturingservers/finalizers
  verbs:
  - update
- apiGroups:
  - fdo.example.com
  resources:
  - fdomanufacturingservers/status
  verbs:
  - get
  - patch
  - update
