apiVersion: v1
kind: ConfigMap
metadata:
  name: fdo-serviceinfo-api-config
  namespace: fdo-operator
data:
  serviceinfo-api-server.yml: |
    bind: 0.0.0.0:8083
    device_specific_store_driver:
      Directory:
        path: /etc/fdo/device_specific_serviceinfo
    service_info:
      initial_user:
        username: admin
        sshkeys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJDdZCX3m3Z1gPeovUsM3Rg6tNNNJsGNqyfYw42jX7Mp test
    service_info_auth_token: "ExampleAuthToken"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdo-serviceinfo-api-deployment
  namespace: fdo-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdo-serviceinfo-api
  template:
    metadata:
      labels:
        app: fdo-serviceinfo-api
    spec:
      containers:
      - name: fdo-serviceinfo-api-server
        image: quay.io/vemporop/fdo-serviceinfo-api-server:1.0
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        ports:
          - containerPort: 8083
        volumeMounts:
        - name: config
          mountPath: /etc/fdo/serviceinfo-api-server.conf.d
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: fdo-serviceinfo-api-config
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: fdo-serviceinfo-api-service
  namespace: fdo-operator
spec:
  selector:
    app: fdo-serviceinfo-api
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: fdo-serviceinfo-api
  namespace: fdo-operator
spec:
  host: fdo-serviceinfo-api.apps-crc.testing
  to:
    kind: Service
    name: fdo-serviceinfo-api-service
  port:
    targetPort: 8083
  wildcardPolicy: None