# permissions for end users to edit fdomanufacturingservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fdomanufacturingserver-editor-role
rules:
- apiGroups:
  - fdo.redhat.com
  resources:
  - fdomanufacturingservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fdo.redhat.com
  resources:
  - fdomanufacturingservers/status
  verbs:
  - get
