# permissions for end users to view fdoonboardingservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fdoonboardingserver-viewer-role
rules:
- apiGroups:
  - fdo.redhat.com
  resources:
  - fdoonboardingservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fdo.redhat.com
  resources:
  - fdoonboardingservers/status
  verbs:
  - get
