# permissions for end users to edit fdoonboardingservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fdoonboardingserver-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fdo-operator
    app.kubernetes.io/part-of: fdo-operator
    app.kubernetes.io/managed-by: kustomize
  name: fdoonboardingserver-editor-role
rules:
- apiGroups:
  - fdo.redhat.com
  resources:
  - fdoonboardingservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fdo.redhat.com
  resources:
  - fdoonboardingservers/status
  verbs:
  - get
