# permissions for end users to edit fdoonboardingservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fdoonboardingserver-editor-role
rules:
- apiGroups:
  - fdo.redhat.com
  resources:
  - fdoonboardingservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fdo.redhat.com
  resources:
  - fdoonboardingservers/status
  verbs:
  - get
