# permissions for end users to view fdorendezvousservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fdorendezvousserver-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fdo-operator
    app.kubernetes.io/part-of: fdo-operator
    app.kubernetes.io/managed-by: kustomize
  name: fdorendezvousserver-viewer-role
rules:
- apiGroups:
  - fdo.redhat.com
  resources:
  - fdorendezvousservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fdo.redhat.com
  resources:
  - fdorendezvousservers/status
  verbs:
  - get
