# permissions for end users to view fdorendezvousservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fdorendezvousserver-viewer-role
rules:
- apiGroups:
  - fdo.redhat.com
  resources:
  - fdorendezvousservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fdo.redhat.com
  resources:
  - fdorendezvousservers/status
  verbs:
  - get
