apiVersion: fdo.redhat.com/v1alpha1
kind: FDOManufacturingServer
metadata:
  labels:
    app.kubernetes.io/name: fdomanufacturingserver
    app.kubernetes.io/instance: fdomanufacturingserver-sample
    app.kubernetes.io/part-of: fdo-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: fdo-operator
  name: fdomanufacturingserver-sample
spec:
  # TODO(user): Add fields here
